
import { Category, FoodItem, MeasureUnit } from './types.ts';

export const MEASURE_GRAMS: Record<MeasureUnit, number> = {
  'Grama': 1,
  '100g': 100,
  '200g': 200,
  '300g': 300,
  '400g': 400,
  '500g': 500,
  '600g': 600,
  '1kg': 1000,
  'Colher Cafe': 2,
  'Colher Cha': 5,
  'Colher Sobremesa': 10,
  'Colher Sopa': 15,
  'Colher Servir': 30,
  'Concha Pequena': 60,
  'Concha Media': 100,
  'Concha Grande': 150,
  'Xicara': 240,
  'Copo Americano': 190,
  'Unidade': 50, 
  'Unidade P': 50,
  'Unidade M': 100,
  'Unidade G': 150,
  'Fatia Fina': 20,
  'Fatia Grossa': 40,
};

export const FOOD_DATABASE: FoodItem[] = [
  { id: '1', name: 'Arroz Branco Cozido', emoji: '🍚', category: Category.CARBOIDRATOS, calories: 128, protein: 2.5, carbs: 28.1, fat: 0.2, fiber: 1.6 },
  { id: '2', name: 'Feijão Carioca Cozido', emoji: '🫘', category: Category.CARBOIDRATOS, calories: 76, protein: 4.8, carbs: 13.6, fat: 0.5, fiber: 8.5 },
  { id: '3', name: 'Peito de Frango Grelhado', emoji: '🍗', category: Category.PROTEINAS, calories: 159, protein: 32, carbs: 0, fat: 2.5, fiber: 0 },
  { id: '4', name: 'Carne Moída (Patinho)', emoji: '🥩', category: Category.PROTEINAS, calories: 219, protein: 35.9, carbs: 0, fat: 7.3, fiber: 0 },
  { id: '5', name: 'Ovo Cozido', emoji: '🥚', category: Category.PROTEINAS, calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0 },
  { id: '6', name: 'Tapioca (Goma)', emoji: '🫓', category: Category.CARBOIDRATOS, calories: 240, protein: 0, carbs: 60, fat: 0, fiber: 0 },
  { id: '7', name: 'Açaí (Polpa)', emoji: '🥣', category: Category.FRUTAS, calories: 60, protein: 0.8, carbs: 6.2, fat: 3.9, fiber: 2.6 },
  { id: '8', name: 'Banana Nanica', emoji: '🍌', category: Category.FRUTAS, calories: 92, protein: 1.4, carbs: 23.8, fat: 0.1, fiber: 2.0 },
  { id: '9', name: 'Alface Crespa', emoji: '🥬', category: Category.VEGETAIS, calories: 11, protein: 1.3, carbs: 1.7, fat: 0.2, fiber: 1.8 },
  { id: '10', name: 'Tomate Salada', emoji: '🍅', category: Category.VEGETAIS, calories: 15, protein: 1.1, carbs: 3.1, fat: 0.2, fiber: 1.2 },
  { id: '11', name: 'Batata Doce Cozida', emoji: '🍠', category: Category.CARBOIDRATOS, calories: 77, protein: 0.6, carbs: 18.4, fat: 0.1, fiber: 2.2 },
  { id: '12', name: 'Tilápia Grelhada', emoji: '🐟', category: Category.PROTEINAS, calories: 128, protein: 26, carbs: 0, fat: 2.7, fiber: 0 },
  { id: '13', name: 'Cuscuz de Milho', emoji: '🌽', category: Category.CARBOIDRATOS, calories: 113, protein: 2.2, carbs: 25, fat: 0.5, fiber: 2.1 },
  { id: '14', name: 'Macarrão Espaguete', emoji: '🍝', category: Category.CARBOIDRATOS, calories: 157, protein: 5.8, carbs: 30.7, fat: 0.9, fiber: 1.8 },
  { id: '15', name: 'Pão Francês', emoji: '🥖', category: Category.CARBOIDRATOS, calories: 300, protein: 8, carbs: 58, fat: 3, fiber: 2.3 },
  { id: '16', name: 'Queijo Minas Frescal', emoji: '🧀', category: Category.PROTEINAS, calories: 243, protein: 17.4, carbs: 3.2, fat: 17.2, fiber: 0 },
  { id: '17', name: 'Leite Integral', emoji: '🥛', category: Category.PROTEINAS, calories: 60, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0 },
  { id: '18', name: 'Manteiga', emoji: '🧈', category: Category.GORDURAS, calories: 717, protein: 0.8, carbs: 0, fat: 81, fiber: 0 },
  { id: '19', name: 'Azeite de Oliva', emoji: '🫒', category: Category.GORDURAS, calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0 },
  { id: '20', name: 'Abacate', emoji: '🥑', category: Category.FRUTAS, calories: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7 },
  { id: '21', name: 'Coxão Mole Cozido', emoji: '🥩', category: Category.PROTEINAS, calories: 219, protein: 32, carbs: 0, fat: 9, fiber: 0 },
  { id: '22', name: 'Sobrecoxa de Frango Assada', emoji: '🍗', category: Category.PROTEINAS, calories: 233, protein: 24, carbs: 0, fat: 15, fiber: 0 },
  { id: '23', name: 'Iogurte Natural', emoji: '🍦', category: Category.PROTEINAS, calories: 51, protein: 4.1, carbs: 5, fat: 3, fiber: 0 },
  { id: '24', name: 'Castanha do Pará', emoji: '🌰', category: Category.GORDURAS, calories: 656, protein: 14, carbs: 12, fat: 66, fiber: 7.5 },
  { id: '25', name: 'Aveia em Flocos', emoji: '🌾', category: Category.CARBOIDRATOS, calories: 389, protein: 16, carbs: 66, fat: 6.9, fiber: 10 },
  { id: '26', name: 'Brocolis Cozido', emoji: '🥦', category: Category.VEGETAIS, calories: 25, protein: 2.1, carbs: 4.4, fat: 0.3, fiber: 3.4 },
  { id: '27', name: 'Cenoura Cozida', emoji: '🥕', category: Category.VEGETAIS, calories: 35, protein: 0.8, carbs: 8.2, fat: 0.2, fiber: 2.8 },
  { id: '28', name: 'Beterraba Cozida', emoji: '🍅', category: Category.VEGETAIS, calories: 44, protein: 1.7, carbs: 10, fat: 0.1, fiber: 2.8 },
  { id: '29', name: 'Chuchu Cozido', emoji: '🍈', category: Category.VEGETAIS, calories: 19, protein: 0.4, carbs: 4.5, fat: 0.1, fiber: 1.1 },
  { id: '30', name: 'Abobora Cozida', emoji: '🎃', category: Category.VEGETAIS, calories: 26, protein: 1, carbs: 6.5, fat: 0.1, fiber: 0.5 },
  { id: '31', name: 'Mandioca Cozida', emoji: '🥔', category: Category.CARBOIDRATOS, calories: 125, protein: 0.6, carbs: 30, fat: 0.3, fiber: 1.6 },
  { id: '32', name: 'Milho Verde Cozido', emoji: '🌽', category: Category.CARBOIDRATOS, calories: 108, protein: 3.3, carbs: 25, fat: 1.3, fiber: 2.4 },
  { id: '33', name: 'Laranja Pêra', emoji: '🍊', category: Category.FRUTAS, calories: 47, protein: 0.9, carbs: 11.7, fat: 0.1, fiber: 2.4 },
  { id: '34', name: 'Maçã Fuji', emoji: '🍎', category: Category.FRUTAS, calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2, fiber: 2.4 },
  { id: '35', name: 'Mamão Papaia', emoji: '🥭', category: Category.FRUTAS, calories: 43, protein: 0.5, carbs: 10.8, fat: 0.3, fiber: 1.7 },
  { id: '36', name: 'Melancia', emoji: '🍉', category: Category.FRUTAS, calories: 30, protein: 0.6, carbs: 7.5, fat: 0.1, fiber: 0.4 },
  { id: '37', name: 'Uva Italiana', emoji: '🍇', category: Category.FRUTAS, calories: 69, protein: 0.7, carbs: 18, fat: 0.1, fiber: 0.9 },
  { id: '38', name: 'Manga Palmer', emoji: '🥭', category: Category.FRUTAS, calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6 },
  { id: '39', name: 'Presunto Cozido', emoji: '🥓', category: Category.INDUSTRIALIZADOS, calories: 145, protein: 16.5, carbs: 2, fat: 8, fiber: 0 },
  { id: '40', name: 'Salsicha de Frango', emoji: '🌭', category: Category.INDUSTRIALIZADOS, calories: 215, protein: 12, carbs: 4.5, fat: 17, fiber: 0 },
];
